apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: expence
  labels:
    component: frontend
    project: expence
    tier: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expence
  labels:
    component: frontend
    project: expence
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
      project: expence
      tier: web
  template:
    metadata:
      labels:
        component: frontend
        project: expence
        tier: web
    spec:
      containers:
        - name: frontend
          image: prenay/frontend
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expence
  labels:
    component: frontend
    project: expence
    tier: web
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: expence
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
