apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    project: expence
    purpose: multi-container-pod-demo
spec:
  containers:
  - name: nginx
    image: nginx
  - name: alpine
    image: alpine      